language: csharp
mono:
  - beta
solution: OTAPI.Server.sln
install:
  - mozroots --import --sync
  - sudo apt-get install unzip
  - nuget restore OTAPI.Server.sln
script:
  - wget -O server.zip https://terraria.org/api/download/pc-dedicated-server/terraria-server-1423.zip
  - unzip server.zip -d tmp_server_zip
  - cp "tmp_server_zip/1423/Windows/TerrariaServer.exe" wrap/TerrariaServer/TerrariaServer.exe
  - xbuild /p:Configuration=Debug OTAPI.Server.sln
